export const beforestSlides = [
  { number: 1, id: "beforest-overview", team: "Beforest Bulletin", title: "Opening Overview", path: "/beforest/intro.html" },
  { number: 2, id: "hospitality-intro", team: "Hospitality", title: "Hospitality", path: "/beforest/hospitality/slide-00-intro.html" },
  { number: 3, id: "hospitality-cover", team: "Hospitality", title: "Guest Experience", path: "/beforest/hospitality/slide-01-cover.html" },
  { number: 4, id: "hospitality-schema", team: "Hospitality", title: "Activity / Output / Outcome / Impact", path: "/beforest/hospitality/slide-02-schema.html" },
  { number: 5, id: "hospitality-food", team: "Hospitality", title: "Food & Beverage", path: "/beforest/hospitality/slide-03-food.html" },
  { number: 6, id: "hospitality-arrival", team: "Hospitality", title: "Arrival Experience", path: "/beforest/hospitality/slide-04-arrival.html" },
  { number: 7, id: "community-intro", team: "Community Experience", title: "Community Experience", path: "/beforest/community-experience/slide-00-intro.html" },
  { number: 8, id: "community-cover", team: "Community Experience", title: "Three Experience Formats", path: "/beforest/community-experience/slide-01-cover.html" },
  { number: 9, id: "community-schema", team: "Community Experience", title: "Activity / Output / Outcome / Impact", path: "/beforest/community-experience/slide-02-schema.html" },
  { number: 10, id: "community-bhopal", team: "Community Experience", title: "Forest Ranger - Bhopal", path: "/beforest/community-experience/slide-03-bhopal.html" },
  { number: 11, id: "community-mumbai", team: "Community Experience", title: "Starry Nights - Mumbai", path: "/beforest/community-experience/slide-04-mumbai.html" },
  { number: 12, id: "bewild-intro", team: "Bewild", title: "Bewild", path: "/beforest/bewild/slide-00-intro.html" },
  { number: 13, id: "bewild-cover", team: "Bewild", title: "Products & Brand", path: "/beforest/bewild/slide-01-cover.html" },
  { number: 14, id: "bewild-schema", team: "Bewild", title: "Activity / Output / Outcome / Impact", path: "/beforest/bewild/slide-02-schema.html" },
  { number: 15, id: "bewild-storefront", team: "Bewild", title: "Storefront & Products", path: "/beforest/bewild/slide-03-storefront.html" },
  { number: 16, id: "bewild-market", team: "Bewild", title: "Market Presence", path: "/beforest/bewild/slide-04-market.html" },
  { number: 17, id: "bhopal-intro", team: "Bhopal Collective", title: "Bhopal Collective", path: "/beforest/bhopal-collective/slide-00-intro.html" },
  { number: 18, id: "bhopal-cover", team: "Bhopal Collective", title: "Infrastructure & Agriculture", path: "/beforest/bhopal-collective/slide-01-cover.html" },
  { number: 19, id: "bhopal-schema", team: "Bhopal Collective", title: "Activity / Output / Outcome / Impact", path: "/beforest/bhopal-collective/slide-02-schema.html" },
  { number: 20, id: "bhopal-agriculture", team: "Bhopal Collective", title: "Agriculture - Crops", path: "/beforest/bhopal-collective/slide-03-agriculture.html" },
  { number: 21, id: "bhopal-experience", team: "Bhopal Collective", title: "First Forest Ranger Experience", path: "/beforest/bhopal-collective/slide-04-experience.html" },
  { number: 22, id: "mumbai-intro", team: "Mumbai Collective", title: "Mumbai Collective", path: "/beforest/mumbai-collective/slide-00-intro.html" },
  { number: 23, id: "mumbai-cover", team: "Mumbai Collective", title: "Field & Experiences", path: "/beforest/mumbai-collective/slide-01-cover.html" },
  { number: 24, id: "mumbai-field", team: "Mumbai Collective", title: "Field Work", path: "/beforest/mumbai-collective/slide-03-field.html" },
  { number: 25, id: "mumbai-protection", team: "Mumbai Collective", title: "Protection", path: "/beforest/mumbai-collective/slide-04-protection.html" },
  { number: 26, id: "mumbai-experience", team: "Mumbai Collective", title: "Starry Nights Experience", path: "/beforest/mumbai-collective/slide-05-experience.html" },
  { number: 27, id: "hammiyala-intro", team: "Hammiyala Collective", title: "Hammiyala Collective", path: "/beforest/hammiyala-collective/slide-00-intro.html" },
  { number: 28, id: "hammiyala-cover", team: "Hammiyala Collective", title: "Overview", path: "/beforest/hammiyala-collective/slide-01-cover.html" },
  { number: 29, id: "hammiyala-schema", team: "Hammiyala Collective", title: "Activity / Output / Outcome / Impact", path: "/beforest/hammiyala-collective/slide-02-schema.html" },
  { number: 30, id: "hammiyala-crop", team: "Hammiyala Collective", title: "Crop Care", path: "/beforest/hammiyala-collective/slide-03-crop.html" },
  { number: 31, id: "hammiyala-boundary", team: "Hammiyala Collective", title: "Boundary & Survey", path: "/beforest/hammiyala-collective/slide-04-boundary.html" },
  { number: 32, id: "hammiyala-infra", team: "Hammiyala Collective", title: "Infrastructure", path: "/beforest/hammiyala-collective/slide-05-infra.html" },
  { number: 33, id: "bodakonda-intro", team: "Bodakonda Collective / Hyderabad", title: "Bodakonda / Hyderabad", path: "/beforest/bodakonda-collective/slide-00-intro.html" },
  { number: 34, id: "bodakonda-cover", team: "Bodakonda Collective / Hyderabad", title: "Terrace Farming", path: "/beforest/bodakonda-collective/slide-01-cover.html" },
  { number: 35, id: "bodakonda-schema", team: "Bodakonda Collective / Hyderabad", title: "Activity / Output / Outcome / Impact", path: "/beforest/bodakonda-collective/slide-02-schema.html" },
  { number: 36, id: "bodakonda-farming", team: "Bodakonda Collective / Hyderabad", title: "Farming & Rain", path: "/beforest/bodakonda-collective/slide-03-farming.html" },
  { number: 37, id: "bodakonda-systems", team: "Bodakonda Collective / Hyderabad", title: "Systems", path: "/beforest/bodakonda-collective/slide-04-systems.html" },
  { number: 38, id: "bodakonda-biodiversity", team: "Bodakonda Collective / Hyderabad", title: "Biodiversity & Volunteers", path: "/beforest/bodakonda-collective/slide-05-biodiversity.html" },
  { number: 39, id: "poomaale1-intro", team: "Poomaale 1.0", title: "Poomaale 1.0", path: "/beforest/poomaale-1-0/slide-00-intro.html" },
  { number: 40, id: "poomaale1-cover", team: "Poomaale 1.0", title: "Major Harvest", path: "/beforest/poomaale-1-0/slide-01-cover.html" },
  { number: 41, id: "poomaale1-schema", team: "Poomaale 1.0", title: "Activity / Output / Outcome / Impact", path: "/beforest/poomaale-1-0/slide-02-schema.html" },
  { number: 42, id: "poomaale1-harvest", team: "Poomaale 1.0", title: "Coffee Harvest", path: "/beforest/poomaale-1-0/slide-03-harvest.html" },
  { number: 43, id: "poomaale1-infra", team: "Poomaale 1.0", title: "Infrastructure", path: "/beforest/poomaale-1-0/slide-04-infra.html" },
  { number: 44, id: "poomaale2-intro", team: "Poomaale 2.0", title: "Poomaale 2.0", path: "/beforest/poomaale-2-0/slide-00-intro.html" },
  { number: 45, id: "poomaale2-cover", team: "Poomaale 2.0", title: "Field Readiness", path: "/beforest/poomaale-2-0/slide-01-cover.html" },
  { number: 46, id: "poomaale2-schema", team: "Poomaale 2.0", title: "Activity / Output / Outcome / Impact", path: "/beforest/poomaale-2-0/slide-02-schema.html" },
  { number: 47, id: "poomaale2-crop", team: "Poomaale 2.0", title: "Crop Management", path: "/beforest/poomaale-2-0/slide-03-crop.html" },
  { number: 48, id: "poomaale2-safety", team: "Poomaale 2.0", title: "Safety", path: "/beforest/poomaale-2-0/slide-04-safety.html" },
  { number: 49, id: "cds-intro", team: "CD&S", title: "CD&S", path: "/beforest/cds/slide-00-intro.html" },
  { number: 50, id: "cds-cover", team: "CD&S", title: "Landscape Stories", path: "/beforest/cds/slide-01-cover.html" },
  { number: 51, id: "cds-schema", team: "CD&S", title: "Activity / Output / Outcome / Impact", path: "/beforest/cds/slide-02-schema.html" },
  { number: 52, id: "cds-gis", team: "CD&S", title: "GIS & Mapping", path: "/beforest/cds/slide-03-gis.html" },
  { number: 53, id: "cds-tools", team: "CD&S", title: "Tools & Resources", path: "/beforest/cds/slide-04-tools.html" },
  { number: 54, id: "hr-intro", team: "Human Resources", title: "Human Resources", path: "/beforest/human-resources/slide-00-intro.html" },
  { number: 55, id: "hr-cover", team: "Human Resources", title: "People & Culture", path: "/beforest/human-resources/slide-01-cover.html" },
  { number: 56, id: "hr-schema", team: "Human Resources", title: "Activity / Output / Outcome / Impact", path: "/beforest/human-resources/slide-02-schema.html" },
  { number: 57, id: "hr-onboarding", team: "Human Resources", title: "New Hires", path: "/beforest/human-resources/slide-03-onboarding.html" },
  { number: 58, id: "hr-fitness", team: "Human Resources", title: "Fitness Sankalp", path: "/beforest/human-resources/slide-04-fitness.html" },
  { number: 59, id: "bi-intro", team: "BI / Business Intelligence", title: "BI / Business Intelligence", path: "/beforest/bi/slide-00-intro.html" },
  { number: 60, id: "bi-cover", team: "BI / Business Intelligence", title: "Automation Overview", path: "/beforest/bi/slide-01-cover.html" },
  { number: 61, id: "bi-openclaw", team: "BI / Business Intelligence", title: "Openclaw - Autonomous Assistant", path: "/beforest/bi/slide-02-openclaw.html" },
  { number: 62, id: "bi-schema", team: "BI / Business Intelligence", title: "Activity / Output / Outcome / Impact", path: "/beforest/bi/slide-03-schema.html" },
  { number: 63, id: "bi-workflows", team: "BI / Business Intelligence", title: "The 4 Workflows", path: "/beforest/bi/slide-04-workflows.html" },
  { number: 64, id: "bi-thankyou", team: "BI / Business Intelligence", title: "Thank You", path: "/beforest/bi/slide-05-thankyou.html" }
];
